

-- CHÚ Ý: KHONG PHÁN TÁN ĐƯỢC VS PHIÊN BẢN THÁP


create TYPE [dbo].[TYPE_BO_DE] AS TABLE(
	CAUHOI INT NULL,
	TRINHDO CHAR(1) NULL,
	[NOIDUNG] [ntext] NULL,
	[A] [ntext] NULL,
	[B] [ntext] NULL,
	[C] [ntext] NULL,
	[D] [ntext] NULL,
	[DAP_AN] [char](1) NULL
)
GO


create PROC [dbo].[SP_INSERT_BODE]
  @BODE TYPE_BO_DE READONLY,
  @MAGV CHAR(10),
  @MAMH CHAR(10)
AS
BEGIN
MERGE INTO BODE AS Target
USING (SELECT CAUHOI,TRINHDO, NOIDUNG,A,B,C,D,DAP_AN FROM @BODE)AS Source
ON Target.CAUHOI= Source.CAUHOI
WHEN MATCHED THEN
  UPDATE SET TARGET.MAMH =@MAMH, TARGET.MAGV=@MAGV,
             TARGET.NOIDUNG=SOURCE.NOIDUNG, TARGET.A=SOURCE.A,
			 TARGET.B=SOURCE.B,TARGET.C=SOURCE.C,
			 TARGET.D=SOURCE.D,TARGET.DAP_AN=SOURCE.DAP_AN,
			 TARGET.TRINHDO=SOURCE.TRINHDO
WHEN NOT MATCHED THEN

 INSERT (MAMH, TRINHDO, NOIDUNG, A,B,C,D,DAP_AN,MAGV)
   VALUES (@MAMH,Source.TRINHDO,Source.NOIDUNG,Source.A,Source.B,Source.C,Source.D,Source.DAP_AN,@MAGV);
END

GO
--SELECT BO DE
alter PROC SP_SELECT_BO_DE
  @MAGV CHAR(5),
  @MAMH CHAR(8)
  AS
 SELECT STT = row_number() OVER (ORDER BY CAUHOI),CAUHOI,TRINHDO,NOIDUNG,A,B,C,D,DAP_AN
 FROM BODE
 WHERE MAGV = @MAGV AND MAMH = @MAMH
  order by CAUHOI
GO
exec SP_SELECT_BO_DE 'th101','mmtcb'
GO

DECLARE @BODE1 AS TYPE_BO_DE
INSERT INTO @BODE1 VALUES(1,1,'A','nd2','A','B','C','D','A')
INSERT INTO @BODE1 VALUES(2,1000,'A','ND','A','B','C','D','A')
INSERT INTO @BODE1 VALUES(3,1001,'A','ND','A','B','C','D','A')
INSERT INTO @BODE1 VALUES(4,1002,'A','ND','A','B','C','D','A')

EXEC SP_INSERT_BODE @BODE1,'TH123','MMTCB'



SELECT * FROM BODE ORDER BY CAUHOI DESC
DELETE FROM BODE WHERE CAUHOI > 220

update bode 
set magv = 'th101'
where magv = 'th123'

--ALTER PROC [dbo].[SP_INSERT_BODE]
--  @BODE TYPE_BO_DE READONLY,
--  @MAGV CHAR(5),
--  @MAMH CHAR(8),
--  @MATRINHDO CHAR(1)
--AS
--BEGIN
--	DECLARE @soCauHoi INT
--	SELECT @soCauHoi= MAX(CAUHOI) FROM BODE
--	insert into BODE(CAUHOI,MAMH,TRINHDO,NOIDUNG,A,B,C,D,DAP_AN,MAGV)
--	SELECT cauhoi = @soCauHoi + row_number() OVER (ORDER BY STT), @MAMH,@MATRINHDO, NOIDUNG,A,B,C,D,DAP_AN,@MAGV
--	FROM @BODE
--END
--