CREATE PROC [dbo].[sp_tim_thong_tin_thi]
@MAMH CHAR(8), 
@NGAYTHI DATETIME, 
@LAN INT
AS

BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN_DANGKY WHERE MAMH=@MAMH AND NGAYTHI=@NGAYTHI AND LAN=@LAN )
		SELECT TRINHDO, SOCAUTHI, THOIGIAN FROM GIAOVIEN_DANGKY
		WHERE MAMH=@MAMH AND NGAYTHI=@NGAYTHI AND LAN=@LAN

	ELSE 
		RAISERROR ('Không tìm thấy thông tin thi',16,1)
	
END