create PROC [dbo].[sp_tim_thong_tin_thi]
@MAMH CHAR(8), 
@NGAYTHI char(10), 
@LAN INT,
@MALOP char(10)
AS

BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN_DANGKY WHERE MAMH=@MAMH AND NGAYTHI=@NGAYTHI AND LAN=@LAN )
		SELECT TRINHDO, SOCAUTHI, THOIGIAN FROM GIAOVIEN_DANGKY
		WHERE LAN=@LAN AND MAMH=@MAMH AND NGAYTHI=@NGAYTHI AND MALOP=@MALOP

	ELSE 
		RAISERROR ('Không tìm thấy thông tin thi',16,1)
	
END