

CREATE  PROC [dbo].[SP_XEM_KET_QUA_THI_THONG_TIN_THI]
@MASV CHAR(8),
@MAMH CHAR(5),
@LAN SMALLINT
AS
SELECT TENLOP, HOTEN, TENMH, NGAYTHI = FORMAT( NGAYTHI, 'dd/MM/yyyy', 'en-US' ), LAN = @LAN
FROM (SELECT MASV, HOTEN = HO+ ' '+TEN, MALOP FROM SINHVIEN WHERE MASV = @MASV) SV
	INNER JOIN (SELECT MALOP,TENLOP FROM LOP) L ON SV.MALOP = L.MALOP
	, (SELECT NGAYTHI FROM BANGDIEM WHERE  MAMH = @MAMH AND LAN = @LAN AND MASV = @MASV) DK
	, (SELECT TENMH FROM MONHOC WHERE MAMH =  @MAMH) MH
--test
exec SP_XEM_KET_QUA_THI_THONG_TIN_THI '001','mmtcb',1
GO
CREATE PROC [dbo].[SP_XEM_KET_QUA_THI_CHI_TIET_THI]
@MASV CHAR(8),
@MAMH CHAR(5),
@LAN SMALLINT
AS
DECLARE @IDBANGDIEM INT
SELECT @IDBANGDIEM = IDBANGDIEM FROM BANGDIEM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN
SELECT STT = ROW_NUMBER() OVER( ORDER BY CAUSO),CAUHOI =REPLACE(CONCAT(N'CÂU',STR(CAUSO)),'    ',''), NOIDUNG, 
	CACHONLUA = CAST((N'A.' + CAST(A AS NVARCHAR(MAX)) +
				CHAR(13)+CHAR(10) +N'B.' + CAST(B AS NVARCHAR(MAX)) + 
				CHAR(13)+CHAR(10) +N'C.' +CAST(C AS NVARCHAR(MAX)) +
				CHAR(13)+CHAR(10) +N'D.' +  CAST(D AS NVARCHAR(MAX))) AS NTEXT),DAP_AN, DACHON
FROM CT_BAI_THI 
WHERE IDBANGDIEM = @IDBANGDIEM
GO

CREATE proc SP_DSSV_CO_BAI_THI
@MALOP NCHAR(15),
@MAMH NCHAR(5),
@LAN	INT
as
select SV.MASV, HOTEN,DIEM 
from (select masv, hoten = ho+ ' ' + ten, MALOP from sinhvien WHERE MALOP = @MALOP)sv 
		inner join (SELECT MASV, DIEM FROM BANGDIEM WHERE MAMH = @MAMH AND LAN = @LAN) BD 
		ON SV.MASV = BD.MASV


